--Drop table if exists
DROP TABLE combine2016;
DROP TABLE combine2017;
DROP TABLE combine2018;
DROP TABLE combine2019;
DROP TABLE combine2020;
DROP TABLE draft2016;
DROP TABLE draft2017;
DROP TABLE draft2018;
DROP TABLE draft2019;
DROP TABLE draft2020;

--Create the combine2016 table
CREATE TABLE combine2016(
    Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	School VARCHAR PRIMARY KEY NOT NULL,
	Ht VARCHAR,
	Wt INTEGER,
	40yd FLOAT,
	Vertical FLOAT,
	Bench INTEGER,
	Broad Jump INTEGER,
	3Cone FLOAT,
	Shuttle FLOAT
);

--Create the combine2017 table
CREATE TABLE combine2017(
    Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	School VARCHAR PRIMARY KEY NOT NULL,
	Ht VARCHAR,
	Wt INTEGER,
	40yd FLOAT,
	Vertical FLOAT,
	Bench INTEGER,
	Broad Jump INTEGER,
	3Cone FLOAT,
	Shuttle FLOAT
);

--Create the combine2018 table
CREATE TABLE combine2018(
    Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	School VARCHAR PRIMARY KEY NOT NULL,
	Ht VARCHAR,
	Wt INTEGER,
	40yd FLOAT,
	Vertical FLOAT,
	Bench INTEGER,
	Broad Jump INTEGER,
	3Cone FLOAT,
	Shuttle FLOAT
);

--Create the combine2019 table
CREATE TABLE combine2019(
    Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	School VARCHAR PRIMARY KEY NOT NULL,
	Ht VARCHAR,
	Wt INTEGER,
	40yd FLOAT,
	Vertical FLOAT,
	Bench INTEGER,
	Broad Jump INTEGER,
	3Cone FLOAT,
	Shuttle FLOAT
);

--Create the combine2020 table
CREATE TABLE combine2020(
    Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	School VARCHAR PRIMARY KEY NOT NULL,
	Ht VARCHAR,
	Wt INTEGER,
	40yd FLOAT,
	Vertical FLOAT,
	Bench INTEGER,
	Broad Jump INTEGER,
	3Cone FLOAT,
	Shuttle FLOAT
);

--Create the draft2016 table
CREATE TABLE draft2016(
	Rnd INTEGER,
	Pick # INTEGER,
	NFL team VARCHAR,
	Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	College VARCHAR PRIMARY KEY NOT NULL,
	Conf.  VARCHAR
);

--Create the draft2017 table
CREATE TABLE draft2017(
	Rnd INTEGER,
	Pick # INTEGER,
	NFL team VARCHAR,
	Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	College VARCHAR PRIMARY KEY NOT NULL,
	Conf.  VARCHAR
);

--Create the draft2018 table
CREATE TABLE draft2018(
	Rnd INTEGER,
	Pick # INTEGER,
	NFL team VARCHAR,
	Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	College VARCHAR PRIMARY KEY NOT NULL,
	Conf.  VARCHAR
);

--Create the draft2019 table
CREATE TABLE draft2019(
	Rnd INTEGER,
	Pick # INTEGER,
	NFL team VARCHAR,
	Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	College VARCHAR PRIMARY KEY NOT NULL,
	Conf.  VARCHAR
);

--Create the draft2020 table
CREATE TABLE draft2020(
	Rnd INTEGER,
	Pick # INTEGER,
	NFL team VARCHAR,
	Player VARCHAR PRIMARY KEY NOT NULL,
	Pos VARCHAR PRIMARY KEY NOT NULL,
	College VARCHAR PRIMARY KEY NOT NULL,
	Conf.  VARCHAR
);

